App\Entity\Categoria:
    attributes:
        id:
            groups: ['categorias', 'restaurante', 'restaurantes_list']
        categoria:
            groups: ['categoria', 'restaurantes_list', 'restaurante']