App\Entity\Categoria:
    properties:
        categoria:
          - NotBlank:
              message: 'Debe indicar un nombre de categoria'
          - Length:
              max: 100
              maxMessage: 'El nombre de la categoria es demasido largo'
